version: "3.4"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.12
    ports:
      - "${EXPOSED_MQTT_PORT}:1883"
    command: "mosquitto -c /mosquitto-no-auth.conf"
  postgres:
    image: postgres:13.4
    ports:
      - "${EXPOSED_POSTGRES_PORT}:5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  datacollector:
    image: maven:3.8.3-jdk-11
    ports:
      - "${EXPOSED_DATACOLLECTOR_REST_PORT}:8080"
      - "${EXPOSED_DATACOLLECTOR_WEBSOCKET_PORT}:8081"
    volumes:
      - "./:/datacollector"
      - "./.maven:/root/.m2"
    environment:
      - "MQTT_URL=${MQTT_URL}"
      - "MQTT_USER=${MQTT_USER}"
      - "MQTT_PASSWORD=${MQTT_PASSWORD}"
      - "POSTGRES_URL=${POSTGRES_URL}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    working_dir: "/datacollector"
    command: "${DATACOLLECTOR_CONTAINER_START_COMMAND:-mvn compile quarkus:dev}"
